# Generated by Django 4.0.6 on 2022-07-29 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_message_past_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='past_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.message'),
        ),
    ]
