# Generated by Django 4.0.6 on 2022-08-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Added'), (1, 'Accepted'), (2, 'Frozen'), (3, 'Resolved'), (4, 'Unresolved')], default=0),
        ),
    ]
