# Generated by Django 4.0.6 on 2022-08-08 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='past_message',
        ),
        migrations.AlterField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='helpdesk.ticket'),
        ),
    ]
