version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - /code/
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
  celery:
    restart: always
    build:
      context: .
    command: celery -A api worker -l info
    volumes:
      - /code/
    depends_on:
      - db
      - redis
      - web
volumes:
  pgdata:
